✨ add resources
cosmoart/Freesets pull request #13
Opened 2024-02-15 20:08 UTC by JuanPabloDiaz

# Add icons to the resources DB

Issue #12

Be sure to complete and check the following steps:

- [x] My changes were made in the `source-web/src/assets/db` folder.
- [x] The resource(s) is completely or partially free.
- [x] The resource(s) is not already in the database.
- [x] All resources have an id, order, name, link and img.
- [x] The ids and urls of the images are not repeated.

2024-02-16 01:50 UTC, cosmoart commented
Thank you for your interest in contributing, before accepting the pull request I have some suggestions:

- To make it easier to read the new resources, use the same indentation of the file (1 tab).
- For image ids, use more complete names, like "react-icons" or "icon-icons", not 51, 52.

As for "Favicon Generator" and "Real Favicon Generator" it would be better to add them in the "tools" category and deduce their "order" a lot as they are tools with a very circumstantial use.

2024-02-16 20:36 UTC, cosmoart requested changes
Please use an indentation of 1 tab.

2024-02-16 20:36 UTC, cosmoart commented on source-web/src/assets/db/tools.json
> +		"img": "https://res.cloudinary.com/cosmocloudinary/image/upload/freesets/icons/favicon-generator",
The correct url would be: https://res.cloudinary.com/cosmocloudinary/image/upload/freesets/tools/favicon-generator

2024-02-16 20:36 UTC, cosmoart commented on source-web/src/assets/db/tools.json
> +		"img": "https://res.cloudinary.com/cosmocloudinary/image/upload/freesets/icons/real-favicon",
The correct url would be: https://res.cloudinary.com/cosmocloudinary/image/upload/freesets/tools/real-favicon

2024-02-17 12:56 UTC, JuanPabloDiaz commented on source-web/src/assets/db/icons.json
> +		"license": "Free & Paid",
If I'm not mistaken, the license for this product is [MIT](https://github.com/Iconscout/iconscout-plugins/blob/master/LICENSE) @cosmoart

2024-02-17 13:23 UTC, JuanPabloDiaz commented
> Please use an indentation of 1 tab.

My VS code was changing the indention for those files when saving it. I changed my settings to allow only 1 tab indentation, but I don't think that changed anything on the actual project. (I do see the files formatted correctly in my VS code)

2024-02-17 18:05 UTC, cosmoart approved these changes

2024-02-17 18:08 UTC, merged